### ISSUE TITLE
silent parser errors

### ISSUE THREAD

**Issue by bbarker** [purescript-web/purescript-web-dom-parser#1]
Confusingly, parser errors [do not throw](https://stackoverflow.com/questions/31277058/parsefromstring-throws-error-in-ie-but-not-in-chrome). 

From [w3c](https://w3c.github.io/DOM-Parsing/): 
> Let root be a new Element, with its local name set to "parsererror" and its namespace set to "http://www.mozilla.org/newlayout/xml/parsererror.xml".

Should we build this check into the `parseXMLFromString` function, and throw an error if detected? Or should we make a separate function? e.g. `parseXMLFromStringOrThrow`

Thoughts, @toastal @garyb ?

**Comment by garyb** [comment]
It'd be nice to do something other than what the basic API provides here, yeah, as that is pretty terrible.

Does the `parsererror` node contain any information do you know? If so I'd suggest we change the return type to `Effect (Either String Document)` and take the `Left` information from there. If not, `Effect (Maybe Document)` and return `Nothing` on error.

**Comment by bbarker** [comment]
I like `Effect (Either String Document)` and am working toward that in the branch [parseErrorExperiments](https://github.com/purescript-web/purescript-web-dom-parser/tree/parseErrorExperiments). It seems different browsers emit the errors in slightly different ways, just to add to the fun! I'll test Firefox and a few Chromium based browsers.

One issue I came across in the above branch was  https://github.com/purescript-web/purescript-web-dom/issues/9, so I was in fact surfacing nulls at runtime, which should not be possible.
