### ISSUE TITLE
Move position from last to first of DOMParser arg or implemented "flipped" variants

### ISSUE THREAD

**Issue by bbarker** [purescript-web/purescript-web-dom-parser#5]
The [current API](https://github.com/purescript-web/purescript-web-dom-parser/blob/v6.0.0/src/Web/DOM/DOMParser.purs#L30-L30) has `DOMParser` as the last argument; this seems a bit inconvenient for what I imagine to be most uses of partial application (in fact, even if concurrency were an issue for `DOMParser`, afaik, JS is still single threaded afaik, so it can't be an issue - so I can't at the moment imagine ever needing more than one `DOMParser`).

The same applies to XMLSerializer as currently implemented in #4, but will plan to make an isolated release with #4 for those preferring the current order.

If there are conceivably other uses for the current API, now or in the future, then we go with flipped: what's a good alternative to name the flipped functions - appending `Flipped` to the end makes long function names that much longer, so how about just a `'`?

**Comment by hdgarrood** [comment]
I'd suggest just letting people use `flip` if they want a flipped version; the fewer functions we export, the better, I think. I think flipped versions are only really needed if you want to give them operator aliases.

**Comment by garyb** [comment]
☝️ hah I was just writing a reply too.

The convention for putting "the thing at the end" still works better here than the alternative I think, since it allows this kind of usage:

``` purescript
something = do
  result <- parseHTMLFromString "foo" =<< makeDOMParser
  ?x result
```

Which is probably a pretty common pattern over reusing a `DOMParser` value multiple times.

**Comment by bbarker** [comment]
Both good points I hadn't thought of, thanks!
